# SQLite version 3.x
#   gem install sqlite3
#
# Ensure the SQLite 3 gem is defined in your Gemfile
# and run `bundle install`.

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  database: db/<%= Rails.env %>.sqlite3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_PATH", "db/production.sqlite3") %>
